source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StripeForm_Example', :exclusive => true do
  pod "StripeForm", :path => "../"
end

target 'StripeForm_Tests', :exclusive => true do
  pod "StripeForm", :path => "../"

  
end
