# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "FTGValueTransformerDemo" do
	pod 'Mantle', '~> 1.5'
end

target "FTGValueTransformerDemoTests" do
    pod 'Mantle', '~> 1.5'
end

