source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Signal_Example', :exclusive => true do
  pod "Signal", :path => "../"
end

target 'Signal_Tests', :exclusive => true do
  pod "Signal", :path => "../"

  
end
