source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftyMonad_Example', :exclusive => true do
  pod "SwiftyMonad", :path => "../"
end

target 'SwiftyMonad_Tests', :exclusive => true do
  pod "SwiftyMonad", :path => "../"

#  pod 'Quick'
#  pod 'Nimble'
end
